context:
  version: "0.15.5"
  python_min: "3.11"

package:
  name: eko
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/e/eko/eko-${{ version }}.tar.gz
    sha256: e1acb3728b1e15c17e60dcaf92c2e89f6a0448304150193ed4a8297ed1ff5e88

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0
  python:
    entry_points:
      - ekonav = ekomark.navigator:launch_navigator
  noarch: python

requirements:
  host:
    - python >=${{ python_min }},<3.15
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.15
    - pyyaml <7.0,>=6.0
    - lz4 >=4.0.2,<5
    - numba >=0.65.0,<0.66
    - scipy >=1.17.0,<2
    - numpy >=2,<3
    - packaging >=24.1,<25

tests:
  - python:
      imports:
        - eko
        - ekobox


about:
  homepage: https://eko.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Evolution Kernel Operators: EKO is a Python module to solve the DGLAP equations in N-space in terms of Evolution Kernel Operators in x-space.'
  repository: https://github.com/N3PDF/eko

extra:
  recipe-maintainers:
    - scarlehoff
